### ISSUE TITLE
Derailed analysis of APCA

### ISSUE THREAD

**Issue by Myndex** [xi/apca-introduction#15]
I have completed a first pass rebuttal on the "Detailed Analysis" that xi created. Rather that push it as PR, I'll just link to it:

[github.com/Myndex/apca-introduction/blob/main/analysis.md](https://github.com/Myndex/apca-introduction/blob/main/analysis.md)

**Comment by xi** [comment]
I understand that you do not agree with this analysis, but please do not spam this issue tracker. This is not an issue.

**Comment by Myndex** [comment]
It is an issue if you are using this repo to spread false and misleading information.
